### ISSUE TITLE
UEFI / EC firmware 1.11 for X1 Extreme Gen4 (20Y5) missing from LVFS

### ISSUE THREAD

**Issue by ginkel** [fwupd/firmware-lenovo#173]
Hi there,

the [Lenovo support page for the X1E4](https://pcsupport.lenovo.com/de/de/products/laptops-and-netbooks/thinkpad-x-series-laptops/thinkpad-x1-extreme-4th-gen-type-20y5-20y6/downloads/driver-list/component?name=BIOS) lists firmware 1.11 while LVFS only has 1.09 available.

Thanks,
Thilo

**Comment by ginkel** [comment]
s/1.11/1.13/

**Comment by mrhpearson** [comment]
1.11 has been up on LVFS for 2 months - https://fwupd.org/lvfs/firmware/8519 so the orignal bug you're raising seems invalid. Let me know if you weren't able to update to 1.11

1.13 only landed on the Lenovo site 3 days ago. It always takes a while for the update to happen on LVFS as they do extra testing. Just the way it is.

**Comment by ginkel** [comment]
The most recent version I see on LVFS is 1.09: https://fwupd.org/lvfs/devices/com.lenovo.ThinkPadN40ET.firmware

The link you posted renders a "permission denied" error.

**Comment by mrhpearson** [comment]
Ooops - sorry, I was logged in and I have access to some internal pages that aren't generally accessible. My bad.
Turns out I'm having a bad day - I mixed up EC and BIOS firmware - I was looking at https://fwupd.org/lvfs/devices/com.lenovo.ThinkPadN40HT.firmware :(

I've raised an internal ticket: LO-1471 and will get this updated

**Comment by mrhpearson** [comment]
FW is up - I successfully updated both EC and BIOS on mine. Let me know if any issues

**Comment by ginkel** [comment]
Excellent, thanks a lot!
