### ISSUE TITLE
Firmware missing for most devices on Thinkpad T14 Gen 4 Intel

### ISSUE THREAD

**Issue by c0deaddict** [fwupd/firmware-lenovo#358]
```
$ fwupdmgr get-updates
Devices with no available firmware updates:
 • ELAN0676:00 04F3:3195
 • Integrated Camera
 • Intel Management Engine
 • MZVL21T0HDLU-00BLL
 • Prometheus IOTA Config
 • System Firmware
 • UEFI Device Firmware
 • UEFI Device Firmware
 • UEFI Device Firmware
 • UEFI Device Firmware
 • UEFI Device Firmware
 • UEFI Device Firmware
 • UEFI Device Firmware
 • UEFI Device Firmware
 • UEFI Device Firmware
 • UEFI Device Firmware
 • UEFI Device Firmware
 • UEFI Device Firmware
 • UEFI Device Firmware
 • UEFI Device Firmware
 • UEFI Device Firmware
Devices with the latest available firmware version:
 • Prometheus
 • UEFI dbx
No updates available

**Comment by hughsie** [comment]
@mrhpearson that does seem like a lot of ESRT devices!

**Comment by hughsie** [comment]
@c0deaddict that's on AC power and with a fully charged battery, right?

**Comment by c0deaddict** [comment]
Yes, that is correct. Although not *fully* charged, TLP charges it up until around 80%, but I guess that counts as fully charged :)

**Comment by c0deaddict** [comment]
> ESRT

What is an ESRT device?

**Comment by mrhpearson** [comment]
ESRT devices - these are the devices that the BIOS says are available and enumerates in the ESRT table (and you can check under /sys/firmware/efi/esrt). I don't have one of these platforms on hand to check what they all are - but we've been moving more and more to EFI capsule updates but that is quite a long list...I'll have to see what is going on there.

For the origin of this ticket and why no FW is available - my guess is it's because we've not completed Linux enablement of this platform yet. Certification is done and preload testing is ongoing. The FW team like to use our preload image for doing their testing for LVFS releases so it does gate LVFS.

If you brought your system with Windows (as Linux isn't available yet) then you can update FW from that. FW for this platform will be on LVFS for future updates.

Let me know if any objections to closing this.

**Comment by c0deaddict** [comment]
Thanks for your explanation! Unfortunately I don't have a Windows license with the laptop, but I can wait for the certification process to complete to install firmware updates.

Ticket can be closed :heavy_check_mark:

**Comment by kpanic** [comment]
Hey @c0deaddict 👋🏾 
Have you ever solved the problem? I have the same situation and no windows.
My touchpad is lagging and freezing randomly and I would hope that a firmware update would solve it.

Does the same happens to you?

**Comment by c0deaddict** [comment]
Hi @kpanic,

Yes, the problem was solved for me because fwupd is now publishing firmware for Linux. Not all devices in the device tree have updateable firmware though. The current list for me is:

```
Devices with no available firmware updates:
 • Database Key
 • Key Exchange Key
 • 0676:00 04F3:3195
 • Integrated Camera
 • KEK CA
 • Option ROM UEFI CA
 • Prometheus (IOTA Config)
 • TPS DMC Family
 • TPS6598X PD#1
 • UEFI Device Firmware
 • UEFI Device Firmware
 • UEFI Device Firmware
 • UEFI Device Firmware
 • UEFI Device Firmware
 • UEFI Device Firmware
 • UEFI Device Firmware
 • UEFI Device Firmware
 • UEFI Device Firmware
 • UEFI Device Firmware
 • UEFI Device Firmware
 • UEFI Device Firmware
 • UEFI Device Firmware
 • UEFI Device Firmware
 • USB3.0 Hub
 • USB4 Retimer
 • Windows Production PCA
Devices with the latest available firmware version:
 • Intel Management Engine
 • MZVL21T0HDLU-00BLL
 • Prometheus
 • System Firmware
 • TPS6598X PD#0
 • UEFI CA
 • UEFI dbx
```

I don't have issues with my touchpad however. But that doesn't rule out a faulty firmware, since my laptop may have come with a newer or older touchpad firmware than yours. Unfortunately it doesn't look like fwupd will update the touchpad firmware, I believe the `0676:00 04F3:3195` in the "devices with no available firmware update" list is the touchpad device.
