### ISSUE TITLE
Z13 AMD cannot wake from suspend

### ISSUE THREAD

**Issue by CosmicSyntax** [fwupd/firmware-lenovo#422]
Hello -

I am running Fedora 39 (Kernel 6.7.4) on the z13 AMD machine. When I suspend the machine, it seem to sleep just fine.  However, I cannot seem to wake. Open the lid and press keys, and nothing.  The fan seems to start spinning, but the power light continue to blink and nothing is on the screen.

According to the OS, it seems like it's trying to use S3.  But, I don't see any options to use S3 in the bios.
cat /sys/power/mem_sleep
s2idle [deep]

Thanks for your help

**Comment by hughsie** [comment]
Is this anything to do with firmware updates? If not, you might have more luck in the Lenovo linux forums I'm afraid.

**Comment by LordChaos73** [comment]
I'm running Ubuntu 23.10 on this laptop, no issues at all.

```
cat /sys/power/mem_sleep
[s2idle]
```

# System Details Report
---

## Report details
- **Date generated:**                              2024-02-14 10:19:38

## Hardware Information:
- **Hardware Model:**                              Lenovo ThinkPad Z13 Gen 1
- **Memory:**                                      32,0 GiB
- **Processor:**                                   AMD Ryzen™ 7 PRO 6860Z with Radeon™ Graphics × 16
- **Graphics:**                                    AMD Radeon™ Graphics
- **Disk Capacity:**                               (null)

## Software Information:
- **Firmware Version:**                            N3GET64W (1.64 )
- **OS Name:**                                     Ubuntu 23.10
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               45.2
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.5.0-17-generic

**Comment by CosmicSyntax** [comment]
Thank you both for your response. This may be an OS issue then.

**Comment by winstonma** [comment]
@CosmicSyntax I had the same issue on my ZenBook S13 OLED running Ubuntu 22.04. Before replacing /lib/firmware with the [firmware.git](https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/) I had the wake up issue. After the firmware overwrite the issue is gone.

Let me find the instructions for you and update this post later.

EDIT: I followed [How to Update Linux Firmware on Ubuntu 22.04](https://tutorialforlinux.com/2022/12/21/how-to-update-linux-firmware-on-ubuntu-22-04-guide/2/) and overwrite the firmware in the system. After reboot the S2 suspend works. Hope this helps.

EDIT 2: [Other user](https://community.frame.work/t/responded-framework-13-amd-ryzen-resume-from-sleep-on-its-own/44901/5) also solved the wake problem by updating firmware 

EDIT 3: I think it is best to update initramfs after replacing firmware
```
sudo update-initramfs -c -k all
```
