### ISSUE TITLE
Latest T14s gen 3 firmware/X13 gen 3 not available on LVFS

### ISSUE THREAD

**Issue by Jackaed** [fwupd/firmware-lenovo#443]
The latest firmware version (1.40) for the thinkpad t14s gen 3 and x13 gen 3 is not available on LVFS at the moment. As of right now, the most up-to-date version on LVFS is 1.35. Please could this update be added to LVFS? The update can be found here: https://pcsupport.lenovo.com/us/en/products/laptops-and-netbooks/thinkpad-t-series-laptops/thinkpad-t14s-gen-3-type-21cq-21cr/downloads/driver-list/component?name=BIOS%2FUEFI&id=5AC6A815-321D-440E-8833-B07A93E0428C (note it was released april 14th, 2024, latest on LVFS is dated 6th of December).

On LVFS, the latest version does seem to be marked 1.40, but when installed and decoded through `dmidecode` it shows that the BIOS firmware version is 1.35, which I find somewhat confusing.

**Comment by hughsie** [comment]
@mrhpearson https://fwupd.org/lvfs/firmware/85577 for your reference.

**Comment by mrhpearson** [comment]
Hi ,
1.40 is on LVFS, but still under embargo. I'll need to check with the FW team when it will be released to stable - but it's a holiday in China and Japan this week so I won't get an update until next week I'm afraid.
It should be soon. We've got a number of AMD platforms with FW updates lined up - and their testing, review and release process takes quite a long time. I've not heard any issues with the latest (fingers crossed).

The previous versions all got pulled for various reasons which is why they're not showing up (they're all there - but under embargo).
As a note (mostly for myself) - I'm tracking this through LO-2765. Please nudge me if I haven't done an update by end of next week.

**Comment by Jackaed** [comment]
May I ask why it's under embargo on LVFS, given it's been released on the Lenovo website? Does the LVFS release mechanism still need to be tested for this particular update, or is it just a matter of signing things off? 

Thank you for the response and the update!

**Comment by mrhpearson** [comment]
It's just process I'm afraid, they don't do things in parallel unfortunately. What is supposed to happen is:
 - The FW team complete their testing and sign-off for the FW to go on the support site. 
 - Once this is done they run the tests using fwupdmgr to make sure updates via LVFS go smoothly.
 - Once that's completed the FW moves to the stable channel.
 
It's supposed to take ~1 week for the LVFS test/release piece; but we have had cases where it's gotten missed or delayed, so I have had to nag the FW team (and tickets like this are useful).

Overall the process is (slowly) getting better, but there is still plenty of room for improvement. We've been hit more in the last year by general FW release issues (rather than Linux specific).

Mark

**Comment by Jackaed** [comment]
Okay, thanks for the response. On a slightly unrelated note - what's an appropriate channel to attempt to report firmware issues and ask for firmware feature requests? Feels like most "official" support channels are more designed for support people attempting to provide tech support rather than for reporting issues directly to a firmware team - but this seems like an innapropriate channel to use to attempt to achieve that, since it's more for reporting issues related to fwpud rather than the firmware itself, but the official form feels like something of a ghost town.

Glad to hear that the processes are improving though.

**Comment by mrhpearson** [comment]
For FW update issues via LVFS - here is good. There's a few of us on the Lenovo Linux team who monitor.

For more general issues probably the best is the forums (forums.lenovo.com/linux). It's not official support, but again there's a few of the Linux team who will see any postings in the Linux specific channels. You often get to bypass the official support mechanism where, realistically, they don't have much direct experience with Linux.

Mark

**Comment by Jackaed** [comment]
Any updates on this?

**Comment by Jackaed** [comment]
Seems to have just been released! Closing, thank you for sorting this out.
